### PR TITLE
Fix wrong status line error

### PR DESCRIPTION
**Pull request by alvy54**
This fixes issue described in https://github.com/ainformatico/mailinator/issues/2.

### CODE REVIEW

**Comment by ainformatico** [comment]
Seems legit.
Could you add a regression test please?

Thanks for the effort!

**Comment by alvy54** [comment]
@ainformatico sorry if I'm missing something here.  What would you want the test to verify besides what the current spec file is doing?

**Comment by ainformatico** [comment]
We should ensure the same error is not raised therefore a test forcing SSL and checking that the error is not raised.

Sorry for the delay, notifications won't work for me and went on holidays.

**Comment by ainformatico** [comment]
Due to the large delay I'm merging this and if you feel with the energy to open another PR with the test I would be most grateful.

**Pull request merged**
